name := "SharingNotes"
scalaVersion := "2.13.3"
libraryDependencies += "org.scalatest" % "scalatest_2.13" % "3.1.1" % "test"
libraryDependencies += "org.apache.tika" % "tika-core" % "1.24"
libraryDependencies += "org.apache.tika" % "tika-parsers" % "1.24"
libraryDependencies += "org.apache.hadoop" % "hadoop-common" % "2.6.0"
libraryDependencies += "org.apache.commons" % "commons-io" % "1.3.2"
libraryDependencies += "org.apache.hadoop" % "hadoop-hdfs" % "2.6.0"
